version: '3'
services:
  registry:
    build:
      context: ./service-registry
    container_name: registry
    expose:
      - "8761"
  video-service:
    build:
      context: ./video-service
    container_name: video-servie
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost/videocity_video_service
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    expose:
      - "8762"
    depends_on:
      - "registry"
      - "video_db"
  sharing-service:
    build:
      context: ./sharing-service
    container_name: sharing-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost/videocity_recommendation_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    expose:
      - "8763"
    depends_on:
      - "registry"
      - "recommendation_db"
  gateway:
    build:
      context: ./api-gateway
    container_name: gateway
    ports:
    - "127.0.0.1:8080:8760"
    depends_on:
      - registry
      - video-service
      - sharing-service
  video_db:
    image: postgres
    container_name: video_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: videocity_video_service
  recommendation_db:
    image: postgres
    container_name: recommendation_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: videocity_recommendation_service

