server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
    jwt:
      secretKey: D5UmXKGUpmTmNTYsdkgKW1GVrHoHEHNC
      tokenPrefix: Bearer
      expirationDate: 14
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: AUTHENTICATION-SERVICE
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
