server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: VIDEO-SERVICE
          uri: lb://VIDEO-SERVICE
          predicates:
            - Path=/video/**
        - id: RECOMMENDATION-SERVICE
          uri: lb://RECOMMENDATION-SERVICE
          predicates:
            - Path=/recommendation/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
