application:
  youtube:
    apiKey: AIzaSyBuSLsmd7CbdVdmYeBf-qG387XQ_H6c8yE

spring:
  profiles:
    active: development
  application:
    name: VIDEO-SERVICE
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost/videocity_video_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
