application:
  youtube:
    apiKey: AIzaSyBuSLsmd7CbdVdmYeBf-qG387XQ_H6c8yE

spring:
  application:
    name: VIDEO-SERVICE
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost/video_service
    username:
    password:
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
