application:
  youtube:
    apiKey: AIzaSyBuSLsmd7CbdVdmYeBf-qG387XQ_H6c8yE

spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost/video_service
    username:
    password:
    driver-class-name: org.postgresql.Driver