server:
  port: 8081

spring:
  application:
    name: RECOMMENDATION-SERVICE
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost/video_sharing_service
    username:
    password:
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
